sudo: false

language: scala

scala:
  - "2.10.7"
  - "2.11.12"
  - "2.12.12"

jdk: "oraclejdk11"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_c6e4beb91ce9_key -iv $encrypted_c6e4beb91ce9_iv -in travis/secring.asc.enc -out travis/local.secring.asc -d;
    gpg --import travis/local.secring.asc;
    fi

script:
  - "sbt ++$TRAVIS_SCALA_VERSION clean scalastyle test:scalastyle it:scalastyle coverage test it:test coverageReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION publishSigned sonatypeBundleRelease
    on:
      condition: $TRAVIS_PULL_REQUEST = 'false'
      all_branches: true

env:
  global:
    - secure: "Uei/fMutTEtgMXd5/HWb2lpevw9MTwOwviGC8bdSRjlh9t3AkvIHoAl/mboIqhlzkjbDsmOIUvht8vs3BO+VH8uk0uZDQ+fqMMyW0lR+jBkxdARnivz1nxOVmk9NOvSAdSdugzzIoc9aTqKJltBZFFKG7UrqpbXlH0wjWAfLTVIwQ9Wl0jd/wIE2cr/gBARuzR+Ot53EhkuqS3lPtN0jbYEraK1aMIpFKTjb0sNQYnxwJMb6tOLQHF/nSd7BQ9ggn6J5u/380mAZRQopaiA48qlC2WZ1YOpZF81IVM0Ymjw/lDH50GdYCpNg6Xs01GcdVvYUO9N7oXIiFR8w0h39iaoPGMVAz3glJK6HI07614m5OhpakCAhmzqqQXUd7pO55l/Ha0k/YwqVzcKf01DsF64wiCcooE+jP6+P+zFQyrgnLT89tvzE4wslGlbn+0koy5XbJk+/OATvfeJERaXpIgfqcFefp79/UrXFMZpfmF2jIN7JN6Vb9X4AUxxAJX5/McUggshCuskLEfOzTJ6Hn83aF+/M6XdVti9LHG3gZDrgY9Bu6YVyRgkdTX8B43HJ/lQwu5K4J5bpN9feaLIa89YPaY65zv0Q9SQtHEPKOvZsx6NhLYnKfdiMa7bmb5kO1L8ls7SZxJYNZuqDRXYtvqXrOouHUmEeCHr+hjz4MNs="
    - SONATYPE_USERNAME=chris-zen
    - secure: "hT9NY9ic7j1Cno8xtYwL07zZ3lR7hQwo/P/HA4ubJbjPV0ptg9blsJfS35sRP3X1eYN15628jQKgl3J7vwVhClHu3Wfnei6oRjPeH4HLzv0Zry79kX7MaECOckhph/TjDTPug/EUjc6cd4BqVY7Ddg4eZQNJS0Yj3PWooEGuqsCQigZKJ5COuMv36HbDKFo6tXpNUDeW4XZZUuK9rLojNUF3m4lMIg33yk67iEyOloj0+u1w7kboN6MfwMLtIbUQ3C4vfT/jlfXrbP3BxIODZx3SunAm11m1IJIGtl9589ppTzBpjjTdoPcb7+9T17M443yIF1/rmLiWBE40NRDIYPcu1+qwMg0YRQJCbwfRG+MsFI0AIBYiJgSgcMC4forNQF94D/SU60DkLPDtDjJ0rxRul39FdMjfhT3Q58m18qQByohpe68uP3A3MfLFpLO8SJKW2CCFizIGxUlq1cP/qQAM79r9tflDkPZVXc0jXG9F6A2LMDlEGUQnDBuT3kvi3gx/ayzj3EmcUMT4Eb+V6B1KkoOay8lqc1jpogiu7M6SyKU9jzInBCGIkc/jQ1X0cnCz1tXoeSYXYs3RIZz5IZGfpGBJOeJEZjjqIyfSIA7YrmqHcmKFhhMjq/7NkApxA9o4QneyALzQInkvmJZsr1xEckuI6g3MiXbmnBl6RGs="
